use_frameworks!

platform :ios, '10.0'

target 'IosAwnFcmDist_Example' do
  pod 'IosAwnFcmDist', :path => '../'

  target 'IosAwnFcmDist_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
