use_frameworks!

platform :ios, '11.0'

target 'IosAwnFcmDist_Example' do
  pod 'IosAwnCore', '~> 0.7.7'#:path => '../../IosAwnCore/'#
  pod 'IosAwnFcmDist', :path => '../'

  target 'IosAwnFcmDist_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
  end
end
